spring.application.name=bff-agendador-tarefas

usuario.url=localhost:8080/usuario
agendador-tarefas.url=localhost:8081/tarefas
notificacao.url=localhost:8082/email
viacep.url=https://viacep.com.br

server.port=8083

cron.horario = 0 0/5 * * * ?

usuario.email=admin@gmail.com

usuario.senha=1234